[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

build_flags =
  -D USER_SETUP_LOADED
  -include include/User_Setup.h

lib_deps =
  bodmer/TFT_eSPI